#pragma once
#include <unordered_map>

std::shared_ptr<std::unordered_map<USHORT, std::string>> GetUSBVendorIDs()
{
	auto USBVendorIDs = std::make_shared<std::unordered_map<USHORT, std::string>>(std::unordered_map<USHORT, std::string>
	{
		{ 0x0079, "Shenzhen Longshengwei Technology, Co., Ltd."  },
		{ 0x013A, "Aimgene Technology Co., Ltd" },
		{ 0x03CC, "GN OTOMETRICS" },
		{ 0x03E8, "EndPoints Inc." },
		{ 0x04D3, "VidUS, Inc." },
		{ 0x04D4, "LSI Logic Inc." },
		{ 0x04D5, "Forte Technologies, Inc." },
		{ 0x04D6, "Mentor Graphics" },
		{ 0x04D7, "Oki Semiconductor" },
		{ 0x04D8, "Microchip Technology Inc." },
		{ 0x04D9, "Holtek Semiconductor, Inc." },
		{ 0x04DA, "Panasonic Corporation" },
		{ 0x04DB, "Hypertec Ltd." },
		{ 0x04DC, "Huan Hsin Holdings Ltd." },
		{ 0x04DD, "Sharp Corporation" },
		{ 0x04DE, "MindShare, Inc." },
		{ 0x04DF, "ePadLink" },
		{ 0x04E1, "Iiyama Corporation" },
		{ 0x04E2, "Exar Corporation" },
		{ 0x04E3, "Zilog" },
		{ 0x04E4, "ACC Microelectronics" },
		{ 0x04E5, "Promise Technology" },
		{ 0x04E6, "Identiv, Inc." },
		{ 0x04E7, "Elo TouchSystems" },
		{ 0x04E8, "Samsung Electronics Co., Ltd." },
		{ 0x04E9, "PC-Tel, Inc." },
		{ 0x04EA, "Sipex Corporation" },
		{ 0x04EB, "Northstar Systems Corp." },
		{ 0x04EC, "Tokyo Electron Device Limited" },
		{ 0x04ED, "Annabooks" },
		{ 0x04EF, "Pacific Electronic International, Inc." },
		{ 0x04F0, "Daewoo Electronics Co., Ltd." },
		{ 0x04F1, "Victor Company of Japan, Limited" },
		{ 0x04F2, "Chicony Electronics Co., Ltd." },
		{ 0x04F3, "ELAN Microelectronics Corportation" },
		{ 0x04F4, "Harting Elektronik Inc." },
		{ 0x04F5, "Fujitsu-ICL Systems, Inc." },
		{ 0x04F6, "Norand Corporation" },
		{ 0x04F7, "Newnex Technology Corp." },
		{ 0x04F8, "FuturePlus Systems" },
		{ 0x04F9, "Brother Industries, Ltd." },
		{ 0x04FA, "Dallas Semiconductor" },
		{ 0x04FB, "Biostar Microtech Int'l Corp." },
		{ 0x04FC, "SUNPLUS TECHNOLOGY CO., LTD." },
		{ 0x04FD, "Soliton Systems K.K." },
		{ 0x04FE, "PFU Limited" },
		{ 0x04FF, "E-CMOS Corp." },
		{ 0x0500, "Siam United Hi-Tech" },
		{ 0x0501, "Fujikura/DDK" },
		{ 0x0502, "Acer, Inc." },
		{ 0x0503, "Hitachi America Ltd." },
		{ 0x0504, "Hayes Microcomputer Products" },
		{ 0x0505, "Digital Home Corporation" },
		{ 0x0506, "3Com Corporation" },
		{ 0x0507, "Hosiden Corporation" },
		{ 0x0508, "Clarion Co., Ltd." },
		{ 0x0509, "Aztech Systems Ltd" },
		{ 0x050A, "Cinch Connectors" },
		{ 0x050B, "Cable System International" },
		{ 0x050C, "InnoMedia, Inc." },
		{ 0x050D, "Belkin International, Inc." },
		{ 0x050E, "Neon Technology, Inc." },
		{ 0x050F, "KC Technology Inc." },
		{ 0x0510, "Sejin Electron Inc." },
		{ 0x0511, "N*ABLE Technologies, Inc (Data Book)" },
		{ 0x0512, "Hualon Microelectronics Corp." },
		{ 0x0513, "digital-X, Inc." },
		{ 0x0514, "FCI Electronics" },
		{ 0x0515, "ACTC" },
		{ 0x0516, "Longwell Electronics/Longwell Company" },
		{ 0x0517, "Butterfly Communications" },
		{ 0x0518, "EzKEY Corp." },
		{ 0x0519, "Star Micronics Co., LTD" },
		{ 0x0000, "N/A"  }
	});

	return USBVendorIDs;
}
